# Generated by Django 5.1.1 on 2024-10-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_paymentorder_total_paymentorder_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
