# Generated by Django 5.1.1 on 2024-09-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sales',
            field=models.BooleanField(default=False),
        ),
    ]
